site_name: MicroScope
site_description:
site_author: LABGeM Team
repo_url: https://github.com/institut-de-genomique/microscope-user-doc
include_search: true
#use_directory_urls: true
copyright: CeCILL license, Copyright &copy; 2015, CEA/Genoscope - LABGeM
theme: yeti
pages:
- ['index.md', 'The MicroScope Platform']
# MicroScope Platform Overview:
- ['interface.md', 'MicroScope Platform Overview', 'Interface']
- ['requirements.md', 'MicroScope Platform Overview', 'Technical Requirement']
